(function(){
  var app=angular.module('creativea',[
    'ngRoute',
    'creativeaServices',
    'creativeaFactories',
    'creativeaDirectives',
    'creativeaFilters',
    'creativeaControllers'
  ]);
  app.config(['$routeProvider',function($routeProvider){
    $routeProvider
      .when('/test',{
        templateUrl:'views/test.html',
        controller:'TestController',
        controllerAs:'test'
      })
      .when('/welcome',{
        templateUrl:'views/welcome.html',
        controller:'WelcomeController',
        controllerAs:'page'
      })
      .otherwise({redirectTo:'/welcome'});
  }]);
})();
